### ISSUE TITLE
Restart SystemUI when theme changed by scheduler

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [ViperOS/android_packages_apps_Venom#3]
Hi, When system theme changed by manual SystemUI was restart automatically to apply settings(theme settings) to all activities but when theme scheduled it does not restart SystemUI and some activities and elements (Ex: old notifications entry, some apps like google phone, messages and etc...) does not use new theme.
It should restart SystemUI when theme changed automatically.
Thanks.

**Comment by EsromTech** [comment]
This is not a problem, the applications you have mentioned are google prebuilts, they will not follow the original theme of the device, however, if you do not restart automatically you can do the Reboot SystemUI using the reboot menu.
